version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "3000:80"
    restart: unless-stopped

  # Development service (optional)
  portfolio-dev:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
    profiles:
      - dev